Make header
Edjhernandez/project_portfolio pull request #2
Opened 2023-03-09 19:05 UTC by Edjhernandez

## Here we make the follow items:

- Top bar with logo and menu.
- Head line with personal description.

![Screenshot 2023-03-09 155158](https://user-images.githubusercontent.com/109191350/224126141-1d28e6fc-dc6a-4c30-b064-17c44c18d583.png)

Let's work!! 🔢

2023-03-10 01:05 UTC, Albinpirela approved these changes

2023-03-10 01:05 UTC, Albinpirela commented on styles.css
> +  height: 622px;
Great job @Edjhernandez 
 I can notice the quality of your code. Please 
consider changing the metric unit from (px) to (%) to have a responsive result

2023-03-10 01:05 UTC, Albinpirela commented on styles.css
>  }
This selector is basic I suggest that you remove it so that it is cleaner and save lines

2023-03-10 01:05 UTC, Albinpirela commented on styles.css
>    font-size: 32px;
I suggest changing the unit of measure from px to rem 👍

2023-03-11 01:16 UTC, Albinpirela requested changes
great job @Edjhernandez 
I can the notice the quality of your code, Please consider changing 
the metric unit  and remove empty selectors

2023-03-11 15:00 UTC, Edjhernandez commented on styles.css
> +  height: 622px;
Hi @Albinpirela, thanks.
I'll change these units px per %.
I agree with you.

2023-03-11 15:02 UTC, Edjhernandez commented on styles.css
>  }
Thanks! @Albinpirela i am going to delete that class.

2023-03-12 14:00 UTC, Albinpirela requested changes
Great job @Edjhernandez 👍  . I suggest you change the units of measurement in font-size in the line 36, 50, 58, 77, and 85 🐶

2023-03-13 16:10 UTC, Albinpirela approved these changes
great job @Edjhernandez , the pr is approved you can merge 👍

2023-03-13 18:52 UTC, merged